blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/CryptoYogiLLC/migrate-ui-orchestrator/discussions
    about: Please ask and answer questions here.
